#pretrain: '/home/10501001/projects/ActionCLIP/exp/clip_k400/RN50/kinetics400/20211209_225150/model_best.pt' #这里指的是训练好的action-clip
resume:
seed: 1024
data:
    dataset: hmdb51
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 16
#    batch_size: 16
    workers: 8
    gpus: 2
    num_classes: 51
    image_tmpl: 'img_{:05d}.jpg'
#    train_list: '/public/home/ock/video_clip/video-clip/lists/hmdb51/train_rgb_split1.txt' #
#    val_list: '/public/home/ock/video_clip/video-clip/lists/hmdb51/val_rgb_split1.txt' #
    train_list: '/home/10501001/datasets/hmdb51/test_train_splits/hmdb51_train_split_1_rawframes.txt'
    val_list: '/home/10501001/datasets/hmdb51/test_train_splits/hmdb51_val_split_1_rawframes.txt'
    label_list: 'lists/hmdb51_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: RN50  #ViT-B/32 ViT-B/16 RN50
    init: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_hmdb
    sim_header: "Transf"  #Transf   meanP   LSTM   Transf_cls Conv_1D
    fix_text: False
    fix_img: False
    describe:
    use_sis: False
    use_nam: False
solver:
    type: cosine
    epochs: 250
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1