resume:
pretrain:
seed: 1024
data:
  dataset: sth-sthv2
  modality: RGB
  num_segments: 8
  seg_length: 1
  batch_size: 16
  workers: 16
  num_classes: 174
  image_tmpl: 'img_{:05d}.jpg'
#  train_list: '/home/10501001/datasets/K400/train.list'
#  val_list: '/home/10501001/datasets/K400/val.list'
  train_list: '/home/10501001/datasets/sthv2/TrainTestValList/train_videofolder.txt'
  val_list: '/home/10501001/datasets/sthv2/TrainTestValList/val_videofolder.txt'
  label_list: 'lists/sthv2_labels.csv'
  index_bias: 1
  input_size: 224
  randaug:
    N: 2 #2
    M: 9  #9
  random_shift: True
network:
  arch: RN50  #ViT-B/32 ViT-B/16
  init: False
  tsm: False
  drop_out: 0.0
  emb_dropout: 0.0
  type: clip_k400
  sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
  joint: False
  describe:
  is_action: True #是否添加action模块
  use_sis: False
  use_nam: False
solver:
  type: cosine
  epochs: 250
  start_epoch: 0
  epoch_offset: 0
  optim: adamw
  lr: 5.e-3
  lr_warmup_step: 5
  momentum: 0.9
  weight_decay: 0.2
  lr_decay_step: 15
  lr_decay_factor: 0.1
  clip_gradient: 20
  loss_type: nll
  evaluate: False
  ratio: 1
  f_ratio: 10
logging:
  print_freq: 10
  eval_freq: 1